Raise minimum version for preserve_order feature to Rust 1.65
Required by hashbrown 0.15.1.

    error: package `hashbrown v0.15.1` cannot be built because it requires rustc 1.65.0 or newer, while the currently active rustc version is 1.64.0