Improve error on compiling with neither std nor alloc
Before:

    error: expected item, found `"serde_json requires that either `std` (default) or `alloc` feature is enabled"`
     --> src/features_check/error.rs:1:1
      |
    1 | "serde_json requires that either `std` (default) or `alloc` feature is enabled"
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected item

    error[E0407]: method `visit_string` is not a member of trait `Visitor`
       --> src/raw.rs:455:5
        |
    455 |       fn visit_string<E>(self, s: String) -> Result<Self::Value, E>
        |       ^  ------------ help: there is an associated function with a similar name: `visit_str`
        |  _____|
        | |
    456 | |     where
    457 | |         E: de::Error,
    458 | |     {
    459 | |         Ok(RawValue::from_owned(s.into_boxed_str()))
    460 | |     }
        | |_____^ not a member of trait `Visitor`

    error[E0046]: not all trait items implemented, missing: `collect_str`
        --> src/ser.rs:1376:1
         |
    1376 | impl<'a, W: io::Write, F: Formatter> ser::Serializer for RawValueStrEmitter<'a, W, F> {
         | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `collect_str` in implementation
         |
         = help: implement the missing item: `fn collect_str<T>(self, _: &T) -> core::result::Result<<Self as serde::Serializer>::Ok, <Self as serde::Serializer>::Error> where T: Display { todo!() }`

    error[E0046]: not all trait items implemented, missing: `collect_str`
       --> src/value/ser.rs:864:1
        |
    864 | impl serde::ser::Serializer for RawValueEmitter {
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `collect_str` in implementation
        |
        = help: implement the missing item: `fn collect_str<T>(self, _: &T) -> core::result::Result<<Self as serde::Serializer>::Ok, <Self as serde::Serializer>::Error> where T: Display { todo!() }`

    error[E0599]: no method named `visit_string` found for struct `BoxedFromString` in the current scope
       --> src/raw.rs:452:14
        |
    428 | pub struct BoxedFromString;
        | --------------------------- method `visit_string` not found for this
    ...
    452 |         self.visit_string(s.to_owned())
        |              ^^^^^^^^^^^^ method not found in `BoxedFromString`

After:

    error: expected item, found `"serde_json requires that either `std` (default) or `alloc` feature is enabled"`
     --> src/features_check/error.rs:1:1
      |
    1 | "serde_json requires that either `std` (default) or `alloc` feature is enabled"
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected item