Fix needless_borrow clippy lint in test
    error: the borrowed expression implements the required traits
     --> tests/regression/issue1004.rs:6:38
      |
    6 |     let value = serde_json::to_value(&float).unwrap();
      |                                      ^^^^^^ help: change this to: `float`
      |
      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
      = note: `-D clippy::needless-borrow` implied by `-D clippy::all`