Update preserve_order required compiler to 1.38.0 for hashbrown
Required by indexmap introducing a dependency on hashbrown 0.11, which
does not build with rustc 1.36.0.

    error[E0658]: use of unstable library feature 'ptr_cast'
       --> github.com-1ecc6299db9ec823/hashbrown-0.11.2/src/raw/mod.rs:504:57
        |
    504 |         NonNull::new_unchecked(self.table.ctrl.as_ptr().cast())
        |                                                         ^^^^

    error[E0658]: use of unstable library feature 'ptr_cast'
        --> github.com-1ecc6299db9ec823/hashbrown-0.11.2/src/raw/mod.rs:1275:51
         |
    1275 |         NonNull::new_unchecked(self.ctrl.as_ptr().cast())
         |                                                   ^^^^

    error[E0658]: use of unstable library feature 'ptr_cast'
      --> github.com-1ecc6299db9ec823/hashbrown-0.11.2/src/raw/sse2.rs:49:40
       |
    49 |         Group(x86::_mm_loadu_si128(ptr.cast()))
       |                                        ^^^^

    error[E0658]: use of unstable library feature 'ptr_cast'
      --> github.com-1ecc6299db9ec823/hashbrown-0.11.2/src/raw/sse2.rs:59:39
       |
    59 |         Group(x86::_mm_load_si128(ptr.cast()))
       |                                       ^^^^

    error[E0658]: use of unstable library feature 'ptr_cast'
      --> github.com-1ecc6299db9ec823/hashbrown-0.11.2/src/raw/sse2.rs:69:34
       |
    69 |         x86::_mm_store_si128(ptr.cast(), self.0);
       |                                  ^^^^