Remove pre-NLL borrow checker workarounds
NLL has been in use since Rust 1.31 (for edition 2018+) or Rust
1.36 (for edition 2015).

    error[E0505]: cannot move out of `json` because it is borrowed
       --> src/raw.rs:184:29
        |
    180 |             let borrowed = ::from_str::<&Self>(&json)?;
        |                                                 ---- borrow of `json` occurs here
    ...
    184 |         Ok(Self::from_owned(json.into_boxed_str()))
        |                             ^^^^ move out of `json` occurs here

    error[E0499]: cannot borrow `self.formatter` as mutable more than once at a time
       --> src/ser.rs:453:13
        |
    444 |                 formatter: &mut self.formatter,
        |                                 -------------- first mutable borrow occurs here
    ...
    453 |             self.formatter
        |             ^^^^^^^^^^^^^^ second mutable borrow occurs here
    ...
    456 |     }
        |     - first borrow ends here

    error[E0499]: cannot borrow `self.writer` as mutable more than once at a time
       --> src/ser.rs:454:34
        |
    443 |                 writer: &mut self.writer,
        |                              ----------- first mutable borrow occurs here
    ...
    454 |                 .end_string(&mut self.writer)
        |                                  ^^^^^^^^^^^ second mutable borrow occurs here
    ...
    456 |     }
        |     - first borrow ends here