Do all CI builds with old rustc using shim crate
Fixes the following error when testing against a compiler older
than 1.64:

    error: failed to select a version for the requirement `hashbrown = "^0.14"`
    candidate versions found which didn't match: 0.13.2, 0.13.1, 0.12.3, ...
    location searched: crates.io index
    required by package `indexmap v2.0.0`
        ... which satisfies dependency `indexmap = "^2"` of package `serde_json v1.0.97`
        ... which satisfies path dependency `serde_json` of package `serde_json_test v0.0.0`